# Generated by Django 3.1.3 on 2021-11-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
