# Generated by Django 3.1.3 on 2021-11-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211122_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(max_length=300),
        ),
    ]
