# Generated by Django 3.1.3 on 2021-11-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_host'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('receive_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('like', models.ManyToManyField(blank=True, to='likes.Like')),
            ],
        ),
    ]
