# Generated by Django 3.1.3 on 2021-11-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='like',
            field=models.ManyToManyField(blank=True, to='likes.Like'),
        ),
    ]
