# Generated by Django 3.1.3 on 2021-10-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='follow',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
