# Generated by Django 3.1.3 on 2021-11-07 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=120)),
                ('password', models.CharField(default='PASS', max_length=120)),
                ('type', models.CharField(default='admin', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=120)),
                ('github_name', models.CharField(max_length=120)),
                ('password', models.CharField(default='PASS', max_length=120)),
                ('type', models.CharField(default='author', max_length=120)),
                ('host', models.CharField(default='https://i-connect.herokuapp.com/', max_length=160)),
                ('profileImage', models.CharField(max_length=300)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
    ]
