# Generated by Django 3.1.3 on 2021-11-04 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=120)),
                ('password', models.CharField(default='PASS', max_length=120)),
                ('type', models.CharField(default='admin', max_length=120)),
            ],
        ),
    ]
