# Generated by Django 3.1.3 on 2021-10-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='PASS', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='author', max_length=120),
        ),
    ]
