# Generated by Django 3.1.3 on 2021-11-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='host',
        ),
    ]
