# Generated by Django 3.1.3 on 2021-11-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
