# Generated by Django 3.1.3 on 2021-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.CharField(default='https://i-connect.herokuapp.com/', max_length=160),
        ),
    ]
