# Generated by Django 3.1.3 on 2021-11-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211120_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default='625bc8b7-0ce0-420a-a4b4-ce1e70046e6b', unique=True),
        ),
    ]
