# Generated by Django 3.1.3 on 2021-11-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211120_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
