# Generated by Django 3.1.3 on 2021-11-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211126_0701'),
        ('users', '0003_auto_20211126_2055'),
    ]

    operations = [
    ]
