# Generated by Django 3.1.3 on 2021-12-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20211126_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
