# Generated by Django 3.1.3 on 2021-10-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_auto_20211027_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='type',
        ),
    ]
