# Generated by Django 3.1.3 on 2021-11-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('type', models.CharField(default='comment', max_length=120)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(max_length=120)),
                ('published', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.CharField(editable=False, max_length=180, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('type', models.CharField(default='comments', max_length=50)),
                ('page', models.IntegerField(default=1)),
                ('size', models.IntegerField(default=5)),
                ('postId', models.CharField(max_length=180)),
                ('id', models.CharField(editable=False, max_length=180, primary_key=True, serialize=False)),
                ('comments', models.ManyToManyField(to='comments.Comment')),
            ],
        ),
    ]
