# Generated by Django 3.1.3 on 2021-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(editable=False, max_length=180, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', max_length=120),
        ),
    ]
