# Generated by Django 3.1.3 on 2021-11-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20211122_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='postId',
            new_name='post',
        ),
    ]
