# Generated by Django 3.1.3 on 2021-11-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='inbox',
            field=models.BooleanField(default=True),
        ),
    ]
