# The code is from here: https://gist.github.com/RadhikaSheth/727b2143d7d1f693d0be0dfe1a396fa4#file-main-yml
# The author is @Radhika Sheth: https://github.com/RadhikaSheth
name: Django-React-App

on:
  push:
    branches: main 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} 
          heroku_email: ${{secrets.EMAIL}}
          dontautocreate: true
